### ISSUE TITLE
Another weirdo?

### ISSUE THREAD

**Issue by rkarlsba** [jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box#11]
Testing with the default opt.ini (well, default everything, really)

Roys-MacBook-Pro-2529:remix-of-Russian-Doll-Maze-Puzzle-Box roy$ ./main.py
OpenSCAD version 2020.09.03
Traceback (most recent call last):
  File "/Users/roy/src/git/jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box/./main.py", line 647, in <module>
    readOpt()
  File "/Users/roy/src/git/jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box/./main.py", line 563, in readOpt
    version = scad_version()
  File "/Users/roy/src/git/jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box/./main.py", line 81, in scad_version
    return (int(ver[0]), int(ver[1])) if ver else ()
ValueError: invalid literal for int() with base 10: ''
Roys-MacBook-Pro-2529:remix-of-Russian-Doll-Maze-Puzzle-Box roy$

Python 3.9.0 on macOS 10.15.4 (19E266)

any ideas?

**Comment by rkarlsba** [comment]
Similar error on debian buster with slightly older python and openscad versions

roy@smilla:~/src/git/jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box$ ./main.py
OpenSCAD version 2019.01-RC2
Traceback (most recent call last):
  File "./main.py", line 647, in <module>
    readOpt()
  File "./main.py", line 563, in readOpt
    version = scad_version()
  File "./main.py", line 81, in scad_version
    return (int(ver[0]), int(ver[1])) if ver else ()
ValueError: invalid literal for int() with base 10: ''
roy@smilla:~/src/git/jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
roy@smilla:~/src/git/jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box$ python3 --version
Python 3.7.3
roy@smilla:~/src/git/jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box$

**Comment by rkarlsba** [comment]
<pre>
#!/bin/bash
# vim:ts=4:sw=4:sts=4:et:ai:tw=80

# Seems jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box doesn't understand version
# numbers like xx.xx.xx or xx.xx-xx, so this is a quick-and-dirty-fix. Saving
# this to $PWD/fsckup.bin/openscad, chmod +x $PWD/fsckup.bin/openscad and then
# setting the openscad path
#   export OPENSCAD_PATH=$PWD/fsckup.bin/openscad'
# will just override it until the bug is fixed ;)

case "$1" in
    "--version")
        echo 'OpenSCAD version 2020.09'
        ;;
    *)
        /Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD $@
        ;;
esac

**Comment by jmerc77** [comment]
the version check has been an on going problem. only the year is needed so I did an update. hope it works now.

**Comment by rkarlsba** [comment]
it doesn't.
and openscad --help, as used in the script to check for parallelism (which I haven't found on these platforms), openscad writes to stderr, not stdout, so on linux/mac, it won't read anything

**Comment by jmerc77** [comment]
Ok. its been a while as iv'e been working on other things here and there. it looks like it is not working well on linux/mac. for those having issues, please retest on windows so I can see if its a linux thing or an unknown bug over all. also, it would be helpful to have someone assist in debugging on linux and especially mac. i am not a mac user, and this is untested on linux. while i could test on a VM, i don't know much about linux as far as programing. the most i've done in linux was with the RPI and its OS, but only basic stuff.
edit: be sure to use the same openSCAD version accross your tests to see if maybe there's an issue with version check etc.
