### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by rkarlsba** [jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box#5]
Seems there's a typo of sorts in the latest version in git

Roys-MacBook-Pro-1840:remix-of-Russian-Doll-Maze-Puzzle-Box roy$ ./main.py
Traceback (most recent call last):
  File "./main.py", line 516, in <module>
    version = scad_version()
  File "./main.py", line 77, in scad_version
    return (int(ver[0]), int(ver[1]), int(ver[2])) if ver else ()
ValueError: invalid literal for int() with base 10: "b''"
Roys-MacBook-Pro-1840:remix-of-Russian-Doll-Maze-Puzzle-Box roy$

Cowboy-fix:

diff --git a/main.py b/main.py
index bfb4680..c4946fe 100755
--- a/main.py
+++ b/main.py
@@ -74,6 +74,8 @@ def scad_version():
     cmd = [openscad(), "--version"]
     ver=sp.run(cmd,capture_output=True).stdout
     ver=str(ver).replace("\\r","").replace("b'OpenSCAD version ","").replace("\\n'","").replace("-",".").split(".")
+# OpenSCAD version 2015.03-3
+    return (2015,3,3)
     return (int(ver[0]), int(ver[1]), int(ver[2])) if ver else ()

 #runs the scad
Roys-MacBook-Pro-1840:remix-of-Russian-Doll-Maze-Puzzle-Box roy$

**Comment by jmerc77** [comment]
problem is here:
ver=str(ver).replace("\r","").replace("b'OpenSCAD version ","").replace("\n'","").replace("-",".").split(".")

should be:
ver=str(ver).replace("\\r","").replace("b'OpenSCAD version ","").replace("\\n'","").replace("-",".").split(".")

try re-downloading or manually fix it as it is correct on the repo page and in my backup.

**Comment by rkarlsba** [comment]
erm - those two mentioned lines are identical. I just tried to checkout main.py to remove my cowboy fix, and same error occurs.

**Comment by jmerc77** [comment]
i meant:
ver=str(ver).replace("\\r","").replace("b'OpenSCAD version ","").replace("\\n'","").replace("-",".").split(".")

(double backslash)

**Comment by jmerc77** [comment]
ummmm... why the **** are they not posting double backslashes properly!

weirderer

**Comment by rkarlsba** [comment]
> 29. des. 2018 kl. 22.39 skrev jmerc77 <notifications@github.com>:
> 
> ummmm... why the **** are they not posting double backslashes properly!
> 

still fails compiling, though

**Comment by jmerc77** [comment]
hmmm... maybe it is not liking the mac. it would be helpfull to know if it is doing that on a windows from your end too. i suspect it needs more escapement for the '.

**Comment by rkarlsba** [comment]
and linux

roysk@roysk:~/src/git/remix-of-Russian-Doll-Maze-Puzzle-Box$ ./main.py
  File "./main.py", line 393
    matrix.append(f"[{','.join(row)}]")
                                     ^
SyntaxError: invalid syntax

not sure about this

**Comment by rkarlsba** [comment]
btw, the mac is using python 3.7.1 - the linux machine tested, uses 3.5.2

**Comment by jmerc77** [comment]
oh. F'' must be a 3.7 thing. i'll work on that.

**Comment by jmerc77** [comment]
think I got it. took a lot though.

**Comment by rkarlsba** [comment]
almost, but not quite ;) 

Roys-MacBook-Pro-1840:remix-of-Russian-Doll-Maze-Puzzle-Box roy$ ./main.py 
Traceback (most recent call last): 
File "./main.py", line 512, in <module> 
version = scad_version() 
File "./main.py", line 77, in scad_version 
return (int(ver[0]), int(ver[1]), int(ver[2])) if ver else () 
ValueError: invalid literal for int() with base 10: "b''" 
Roys-MacBook-Pro-1840:remix-of-Russian-Doll-Maze-Puzzle-Box roy$ 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Hið góða skaltu í stein höggva, hið illa í snjó rita.

**Comment by rkarlsba** [comment]
roysk@roysk:~/src/git/remix-of-Russian-Doll-Maze-Puzzle-Box$ python3 --version 
Python 3.5.2 
roysk@roysk:~/src/git/remix-of-Russian-Doll-Maze-Puzzle-Box$ ./main.py 
Traceback (most recent call last): 
File "./main.py", line 512, in <module> 
version = scad_version() 
File "./main.py", line 75, in scad_version 
ver=sp.run(cmd,capture_output=True).stdout 
File "/usr/lib/python3.5/subprocess.py", line 693, in run 
with Popen(*popenargs, **kwargs) as process: 
TypeError: __init__() got an unexpected keyword argument 'capture_output' 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Hið góða skaltu í stein höggva, hið illa í snjó rita.

**Comment by jmerc77** [comment]
ok... traded run(...) for Popen(...). still works on my end how about yours?

**Comment by rkarlsba** [comment]
Roys-MacBook-Pro-1840:remix-of-Russian-Doll-Maze-Puzzle-Box roy$ ./main.py 
OpenSCAD version 2015.03-3 
b'' 
Traceback (most recent call last): 
File "./main.py", line 513, in <module> 
version = scad_version() 
File "./main.py", line 78, in scad_version 
return (int(ver[0]), int(ver[1]), int(ver[2])) if ver else () 
ValueError: invalid literal for int() with base 10: "b''" 

on both linux and mac 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Hið góða skaltu í stein höggva, hið illa í snjó rita.

**Comment by jmerc77** [comment]
oh! aha! just what I needed! 
decode("utf-8")

**Comment by rkarlsba** [comment]
Roys-MacBook-Pro-1840:remix-of-Russian-Doll-Maze-Puzzle-Box roy$ ./main.py 
OpenSCAD version 2015.03-3 
Traceback (most recent call last): 
File "./main.py", line 512, in <module> 
version = scad_version() 
File "./main.py", line 77, in scad_version 
return (int(ver[0]), int(ver[1]), int(ver[2])) if ver else () 
ValueError: invalid literal for int() with base 10: '' 
Roys-MacBook-Pro-1840:remix-of-Russian-Doll-Maze-Puzzle-Box roy$ 

Same on linux 

Do you want an account on a linux machine to play around a bit? 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Hið góða skaltu í stein höggva, hið illa í snjó rita.

**Comment by jmerc77** [comment]
made many changes since then. if I were to test on linux, I'd rather do it on my end with VM. I was having issues getting it to work. some of which were due to slow internet. but ill look into it soon because I changed internet providers.

**Comment by jmerc77** [comment]
btw, what were the options used? that seems to help with testing on my end.

**Comment by rkarlsba** [comment]
I don't remember - it's some months ago, and I found https://github.com/revk/PuzzleBox working better.

**Comment by jmerc77** [comment]
ver[2] was unused and was causing problems. so i removed that. seems better now.

**Comment by jmerc77** [comment]
the version check has been an on going problem. only the year is needed so I did an update. hope it works now.

**Comment by jmerc77** [comment]
> Ok. its been a while as iv'e been working on other things here and there. it looks like it is not working well on linux/mac. for those having issues, please retest on windows so I can see if its a linux thing or an unknown bug over all. also, it would be helpful to have someone assist in debugging on linux and especially mac. i am not a mac user, and this is untested on linux. while i could test on a VM, i don't know much about linux as far as programing. the most i've done in linux was with the RPI and its OS, but only basic stuff.
> edit: be sure to use the same openSCAD version accross your tests to see if maybe there's an issue with version check etc.

**Comment by rkarlsba** [comment]
Please see my PR
